### ISSUE TITLE
Logo on website is broken

### ISSUE THREAD

**Issue by pedroapfilho** [system-ui/system-ui.com#6]
<img width="542" alt="Screenshot 2020-08-05 at 13 07 47" src="https://user-images.githubusercontent.com/13142568/89436477-aecdcb00-d71c-11ea-8cff-af17386eb6c1.png">

<img width="523" alt="Screenshot 2020-08-05 at 13 08 24" src="https://user-images.githubusercontent.com/13142568/89436537-c311c800-d71c-11ea-849e-f8caeee0e3c6.png">

**Comment by MrJ33cK** [comment]
Hay

**Comment by MrJ33cK** [comment]
How are you
